In [ ]:
from scripts.load_data import DataLoader
import sys
from pathlib import Path

ANALYZER_DIR = Path.cwd().parent

sys.path.insert(0, str(ANALYZER_DIR.resolve()))

# limpiar cache previo
if "scripts" in sys.modules:
    del sys.modules["scripts"]

In [61]:
loader = DataLoader().load_all()

In [48]:
loader.repositories.head()

,repository_id,repository_name,total_dependencies,total_dependency_vulnerabilities,total_code_vulnerabilities,analyzed_at,analysis_status
0,9991dc2fdc4450f295d3673933856751e7c16bf9,ambari-presto-service,8,2,0,2026-05-07T16:22:15.799748+00:00,completed
1,3e07d4c71e588445c016a7d056d7e15105f9524a,aws-proxy,840,29,0,2026-05-07T16:22:15.799840+00:00,completed
2,72d2d74b93ff1171abcc53e0299a936c62fbe4e4,benchto,76,14,0,2026-05-07T16:22:15.799856+00:00,completed
3,3c1836f3a69c98f75ea3c5cb3054a8e1afcca366,charts,8,0,0,2026-05-07T16:22:15.799867+00:00,completed
4,f3a839464298b1e2648da26706457d7aafd4e777,cla,0,0,0,2026-05-07T16:22:15.799876+00:00,completed

In [49]:
loader.repositories.info()

<class 'pandas.DataFrame'>
RangeIndex: 46 entries, 0 to 45
Data columns (total 7 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   repository_id                     46 non-null     str
 1   repository_name                   46 non-null     str
 2   total_dependencies                46 non-null     int64
 3   total_dependency_vulnerabilities  46 non-null     int64
 4   total_code_vulnerabilities        46 non-null     int64
 5   analyzed_at                       46 non-null     str
 6   analysis_status                   46 non-null     str
dtypes: int64(3), str(4)
memory usage: 6.9 KB

In [50]:
loader.dependencies.head()

,dependency_id,repository_id,repository_name,artifact_name,artifact_version,artifact_type,package_url,cpe,licenses,locations,found_by,metadata,sbom_source,analyzed_at
0,56e7fac50f078364bb8d8b64985476565ddcb706,9991dc2fdc4450f295d3673933856751e7c16bf9,ambari-presto-service,mock,1.0.1,python,pkg:pypi/mock@1.0.1,"[{'cpe': 'cpe:2.3:a:python-mock:python-mock:1.0.1:*:*:*:*:*:*:*', 'source': 'syft-generated'}, {'cpe': 'cpe:2.3:a:python-mock:python_mock:1.0.1:*:*:*:*:*:*:*', 'source': 'syft-generated'}, {'cpe':...",[],"[{'path': '/requirements.txt', 'accessPath': '/requirements.txt', 'annotations': {'evidence': 'primary'}}]",python-package-cataloger,"{'name': 'mock', 'versionConstraint': '==1.0.1', 'virtualPath': None, 'pomProperties': None, 'pomProject': None, 'value': None, 'manifest': None, 'digest': None, 'comment': None, 'resolved': None,...",syft,2026-05-07T16:22:13.610587+00:00
1,56e7fac50f078364bb8d8b64985476565ddcb706,9991dc2fdc4450f295d3673933856751e7c16bf9,ambari-presto-service,mock,1.0.1,python,pkg:pypi/mock@1.0.1,"[{'cpe': 'cpe:2.3:a:python-mock:python-mock:1.0.1:*:*:*:*:*:*:*', 'source': 'syft-generated'}, {'cpe': 'cpe:2.3:a:python-mock:python_mock:1.0.1:*:*:*:*:*:*:*', 'source': 'syft-generated'}, {'cpe':...",[],"[{'path': '/setup.py', 'accessPath': '/setup.py', 'annotations': {'evidence': 'primary'}}]",python-package-cataloger,None,syft,2026-05-07T16:22:13.610620+00:00
2,fa57e5cc7dd7ea22fdf977709cda08b68276e66f,9991dc2fdc4450f295d3673933856751e7c16bf9,ambari-presto-service,nose,1.3.7,python,pkg:pypi/nose@1.3.7,"[{'cpe': 'cpe:2.3:a:python-nose:python-nose:1.3.7:*:*:*:*:*:*:*', 'source': 'syft-generated'}, {'cpe': 'cpe:2.3:a:python-nose:python_nose:1.3.7:*:*:*:*:*:*:*', 'source': 'syft-generated'}, {'cpe':...",[],"[{'path': '/requirements.txt', 'accessPath': '/requirements.txt', 'annotations': {'evidence': 'primary'}}]",python-package-cataloger,"{'name': 'nose', 'versionConstraint': '==1.3.7', 'virtualPath': None, 'pomProperties': None, 'pomProject': None, 'value': None, 'manifest': None, 'digest': None, 'comment': None, 'resolved': None,...",syft,2026-05-07T16:22:13.610628+00:00
3,fa57e5cc7dd7ea22fdf977709cda08b68276e66f,9991dc2fdc4450f295d3673933856751e7c16bf9,ambari-presto-service,nose,1.3.7,python,pkg:pypi/nose@1.3.7,"[{'cpe': 'cpe:2.3:a:python-nose:python-nose:1.3.7:*:*:*:*:*:*:*', 'source': 'syft-generated'}, {'cpe': 'cpe:2.3:a:python-nose:python_nose:1.3.7:*:*:*:*:*:*:*', 'source': 'syft-generated'}, {'cpe':...",[],"[{'path': '/setup.py', 'accessPath': '/setup.py', 'annotations': {'evidence': 'primary'}}]",python-package-cataloger,None,syft,2026-05-07T16:22:13.610635+00:00
4,9fc68aa4cec56911806dc42669f79e68f79538e3,9991dc2fdc4450f295d3673933856751e7c16bf9,ambari-presto-service,sphinx,1.6.3,python,pkg:pypi/sphinx@1.6.3,"[{'cpe': 'cpe:2.3:a:python-sphinx:python-sphinx:1.6.3:*:*:*:*:*:*:*', 'source': 'syft-generated'}, {'cpe': 'cpe:2.3:a:python-sphinx:python_sphinx:1.6.3:*:*:*:*:*:*:*', 'source': 'syft-generated'},...",[],"[{'path': '/requirements.txt', 'accessPath': '/requirements.txt', 'annotations': {'evidence': 'primary'}}]",python-package-cataloger,"{'name': 'Sphinx', 'versionConstraint': '==1.6.3', 'virtualPath': None, 'pomProperties': None, 'pomProject': None, 'value': None, 'manifest': None, 'digest': None, 'comment': None, 'resolved': Non...",syft,2026-05-07T16:22:13.610646+00:00

In [51]:
loader.dependencies.info()

<class 'pandas.DataFrame'>
RangeIndex: 7120 entries, 0 to 7119
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   dependency_id     7120 non-null   str
 1   repository_id     7120 non-null   str
 2   repository_name   7120 non-null   str
 3   artifact_name     7120 non-null   str
 4   artifact_version  7120 non-null   str
 5   artifact_type     7120 non-null   str
 6   package_url       7120 non-null   str
 7   cpe               7120 non-null   object
 8   licenses          7120 non-null   object
 9   locations         7120 non-null   object
 10  found_by          7120 non-null   str
 11  metadata          7028 non-null   object
 12  sbom_source       7120 non-null   str
 13  analyzed_at       7120 non-null   str
dtypes: object(4), str(10)
memory usage: 2.3+ MB

In [52]:
loader.dependencies.isnull().sum()

dependency_id        0
repository_id        0
repository_name      0
artifact_name        0
artifact_version     0
artifact_type        0
package_url          0
cpe                  0
licenses             0
locations            0
found_by             0
metadata            92
sbom_source          0
analyzed_at          0
dtype: int64

In [53]:
loader.dependency_vulnerabilities.head()

,vulnerability_record_id,repository_id,repository,dependency_id,package_name,package_version,package_type,language,purl,location,vulnerability_id,related_cve,severity,cvss_score,epss,risk,cwe,fix_state,fix_versions,description,data_source,namespace,tool,analyzed_at
0,b14d7c0940e22a35b43c46ab40c322db76044c8b,9991dc2fdc4450f295d3673933856751e7c16bf9,ambari-presto-service,c8478ce28dd44e584e619a5f594c3d62d71dfe86,virtualenv,12.0.7,python,python,pkg:pypi/virtualenv@12.0.7,/requirements.txt,GHSA-rqc4-2hc7-8c8v,CVE-2024-53899,High,8.4,0.00226,0.17967,"[CWE-77, CWE-78]",fixed,[20.26.6],virtualenv allows command injection through activation scripts for a virtual environment,https://github.com/advisories/GHSA-rqc4-2hc7-8c8v,github:language:python,grype,2026-05-07T16:22:15.071615+00:00
1,96b3f15b87a70d57873a7ad495a74171321f5ace,9991dc2fdc4450f295d3673933856751e7c16bf9,ambari-presto-service,c8478ce28dd44e584e619a5f594c3d62d71dfe86,virtualenv,12.0.7,python,python,pkg:pypi/virtualenv@12.0.7,/requirements.txt,GHSA-597g-3phw-6986,CVE-2026-22702,Medium,4.5,0.00014,0.00665,"[CWE-59, CWE-362]",fixed,[20.36.1],virtualenv Has TOCTOU Vulnerabilities in Directory Creation,https://github.com/advisories/GHSA-597g-3phw-6986,github:language:python,grype,2026-05-07T16:22:15.071683+00:00
2,7afc9c4cc199b51456e5804929b3dade71de4507,3e07d4c71e588445c016a7d056d7e15105f9524a,aws-proxy,96d52bd1d72b17eeaf560d27d0cf2e9ff47b4df4,netty-handler,4.1.100.Final,java-archive,java,pkg:maven/io.netty/netty-handler@4.1.100.Final,/trino-aws-proxy/target/test-jars/bundle-2.24.6.jar,GHSA-4g8c-wm8x-jfhw,CVE-2025-24970,High,7.5,0.00953,0.71475,[CWE-20],fixed,[4.1.118.Final],SslHandler doesn't correctly validate packets which can lead to native crash when using native SSLEngine,https://github.com/advisories/GHSA-4g8c-wm8x-jfhw,github:language:java,grype,2026-05-07T16:22:15.087269+00:00
3,55ec8300227489681df95a1aa4536cc5cbcbd3ff,3e07d4c71e588445c016a7d056d7e15105f9524a,aws-proxy,acb3dc7ba0cd0f304d8477fb0dc03ea0cc07e75f,netty-handler,4.1.77.Final,java-archive,java,pkg:maven/io.netty/netty-handler@4.1.77.Final,/trino-aws-proxy/target/test-jars/aws-java-sdk-bundle-1.12.262.jar,GHSA-6mjq-h674-j845,CVE-2023-34462,Medium,6.5,0.00998,0.57385,"[CWE-400, CWE-770]",fixed,[4.1.94.Final],netty-handler SniHandler 16MB allocation,https://github.com/advisories/GHSA-6mjq-h674-j845,github:language:java,grype,2026-05-07T16:22:15.087310+00:00
4,a1f2117407e2c6ee6a617b1880c5bd2b079e36c9,3e07d4c71e588445c016a7d056d7e15105f9524a,aws-proxy,49b21f3b1a648530924b2d5a18055b1734a48f30,jackson-databind,2.12.6.1,java-archive,java,pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.12.6.1,/trino-aws-proxy/target/test-jars/aws-java-sdk-bundle-1.12.262.jar,GHSA-jjjh-jjxp-wpff,CVE-2022-42003,High,7.5,0.00377,0.28275,[CWE-502],fixed,[2.12.7.1],Uncontrolled Resource Consumption in Jackson-databind,https://github.com/advisories/GHSA-jjjh-jjxp-wpff,github:language:java,grype,2026-05-07T16:22:15.087330+00:00

In [54]:
loader.dependency_vulnerabilities.info()

<class 'pandas.DataFrame'>
RangeIndex: 722 entries, 0 to 721
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   vulnerability_record_id  722 non-null    str
 1   repository_id            722 non-null    str
 2   repository               722 non-null    str
 3   dependency_id            722 non-null    str
 4   package_name             722 non-null    str
 5   package_version          722 non-null    str
 6   package_type             722 non-null    str
 7   language                 722 non-null    str
 8   purl                     722 non-null    str
 9   location                 722 non-null    str
 10  vulnerability_id         722 non-null    str
 11  related_cve              518 non-null    str
 12  severity                 722 non-null    str
 13  cvss_score               710 non-null    float64
 14  epss                     660 non-null    float64
 15  risk                     722 non-null    float64
 16  cwe                      722 non-null    object
 17  fix_state                722 non-null    str
 18  fix_versions             722 non-null    object
 19  description              722 non-null    str
 20  data_source              722 non-null    str
 21  namespace                722 non-null    str
 22  tool                     722 non-null    str
 23  analyzed_at              722 non-null    str
dtypes: float64(3), object(2), str(19)
memory usage: 507.6+ KB

In [55]:
loader.dependency_vulnerabilities.isnull().sum()

vulnerability_record_id      0
repository_id                0
repository                   0
dependency_id                0
package_name                 0
package_version              0
package_type                 0
language                     0
purl                         0
location                     0
vulnerability_id             0
related_cve                204
severity                     0
cvss_score                  12
epss                        62
risk                         0
cwe                          0
fix_state                    0
fix_versions                 0
description                  0
data_source                  0
namespace                    0
tool                         0
analyzed_at                  0
dtype: int64

In [56]:
loader.code_vulnerabilities.head()

,finding_id,repository_id,rule_id,severity,message,file_path,start_line,end_line,start_column,end_column,kind,tool,analyzed_at
0,9c9ba22e313a210942fe744a63f949808f46c004,539489521a87dff7364bcf49dcb350dcbdebac92,js/xss,warning,Cross-site scripting vulnerability due to [user-provided value](1).,reveal/plugin/notes/speaker-view.html,480,None,31,51,notApplicable,codeql,2026-05-07T16:22:15.658658+00:00
1,af850b84b02440e46b1e948a30698ae08ef0b9b8,539489521a87dff7364bcf49dcb350dcbdebac92,js/xss,warning,Cross-site scripting vulnerability due to [user-provided value](1).,reveal/plugin/notes/speaker-view.html,483,None,31,41,notApplicable,codeql,2026-05-07T16:22:15.658688+00:00
2,b918c447dff5913baacdc04210bca45419a2336a,539489521a87dff7364bcf49dcb350dcbdebac92,js/xss,warning,Cross-site scripting vulnerability due to [user-provided value](1).,reveal/plugin/notes/speaker-view.html,542,None,40,50,notApplicable,codeql,2026-05-07T16:22:15.658713+00:00
3,4f7094fa4ffa379bffff93b2caa48cfe1fee1591,539489521a87dff7364bcf49dcb350dcbdebac92,js/xss,warning,Cross-site scripting vulnerability due to [user-provided value](1).,reveal/plugin/notes/speaker-view.html,548,None,41,52,notApplicable,codeql,2026-05-07T16:22:15.658729+00:00
4,6df6c760e5924059be76ad0a775437fd8195c974,539489521a87dff7364bcf49dcb350dcbdebac92,js/xss-through-dom,warning,[DOM text](1) is reinterpreted as HTML without escaping meta-characters.,reveal/js/controllers/notes.js,43,None,29,117,notApplicable,codeql,2026-05-07T16:22:15.658747+00:00

In [57]:
loader.code_vulnerabilities.info()

<class 'pandas.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   finding_id     23 non-null     str
 1   repository_id  23 non-null     str
 2   rule_id        23 non-null     str
 3   severity       23 non-null     str
 4   message        23 non-null     str
 5   file_path      23 non-null     str
 6   start_line     23 non-null     int64
 7   end_line       0 non-null      object
 8   start_column   23 non-null     int64
 9   end_column     23 non-null     int64
 10  kind           23 non-null     str
 11  tool           23 non-null     str
 12  analyzed_at    23 non-null     str
dtypes: int64(3), object(1), str(9)
memory usage: 8.5+ KB

In [58]:
loader.code_vulnerabilities.isnull().sum()

finding_id        0
repository_id     0
rule_id           0
severity          0
message           0
file_path         0
start_line        0
end_line         23
start_column      0
end_column        0
kind              0
tool              0
analyzed_at       0
dtype: int64