In [7]:
from scripts.metrics import MetricsBuilder
from scripts.load_data import DataLoader
import sys
from pathlib import Path

import pandas as pd

ANALYZER_DIR = Path.cwd().parent

sys.path.insert(0, str(ANALYZER_DIR.resolve()))

for module in list(sys.modules):
    if module == "scripts" or module.startswith("scripts."):
        del sys.modules[module]

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 200)
pd.set_option("display.max_colwidth", 200)


loader = DataLoader().load_all()

metrics = MetricsBuilder(loader)

In [8]:
repository_summary = (
    metrics.repository_summary()
)

repository_summary.head(20)

,repository,total_vulnerabilities,unique_vulnerabilities
20,trino-packages,360,53
6,github-actions,72,47
12,trino-admin,50,27
11,trino,45,32
3,aws-proxy,29,21
10,tempto,25,25
0,539489521a87dff7364bcf49dcb350dcbdebac92,22,8
14,trino-gateway,22,18
19,trino-js-client,17,17
5,docker-images,14,14
4,benchto,14,14
17,trino-hive-apache,13,13
22,trino-rubix,13,13
21,trino-query-ui,9,9
15,trino-go-client,8,7
18,trino-hive-jdbc,7,7
13,trino-coral,4,4
7,grafana-trino,3,3
9,presto-cassandra-server,3,3
23,trino-verifier-queries,3,3

In [9]:
severity_distribution = (
    metrics.severity_distribution()
)

severity_distribution.head(20)

                                  repository normalized_severity  count
57                            trino-packages                HIGH    142
59                            trino-packages              MEDIUM    138
58                            trino-packages                 LOW     68
17                            github-actions              MEDIUM     37
15                            github-actions                HIGH     28
30                                     trino              MEDIUM     25
32                               trino-admin                HIGH     24
0   539489521a87dff7364bcf49dcb350dcbdebac92              MEDIUM     22
34                               trino-admin              MEDIUM     18
28                                     trino                HIGH     15
6                                  aws-proxy              MEDIUM     15
26                                    tempto              MEDIUM     13
56                            trino-packages            CRITICAL     12
38                             trino-gateway                HIGH     12
4                                  aws-proxy                HIGH     11
55                           trino-js-client              MEDIUM     11
40                             trino-gateway              MEDIUM      9
60                            trino-query-ui              MEDIUM      9
24                                    tempto                HIGH      8
11                             docker-images                HIGH      7

In [10]:
repository_risk = (
    metrics.repository_risk()
)

repository_risk.head(20)

normalized_severity,repository,critical_count,high_count,low_count,medium_count,unknown_count,total_vulnerabilities,risk_score
20,trino-packages,12,142,68,138,0,360,830
6,github-actions,3,28,4,37,0,72,177
12,trino-admin,6,24,2,18,0,50,140
11,trino,1,15,4,25,0,45,104
3,aws-proxy,0,11,3,15,0,29,66
10,tempto,3,8,1,13,0,25,66
14,trino-gateway,0,12,1,9,0,22,55
4,benchto,4,6,1,3,0,14,45
17,trino-hive-apache,5,5,1,2,0,13,45
0,539489521a87dff7364bcf49dcb350dcbdebac92,0,0,0,22,0,22,44
19,trino-js-client,0,5,1,11,0,17,38
22,trino-rubix,3,5,2,3,0,13,38
5,docker-images,0,7,1,6,0,14,34
15,trino-go-client,0,5,0,3,0,8,21
18,trino-hive-jdbc,1,2,1,3,0,7,18
21,trino-query-ui,0,0,0,9,0,9,18
7,grafana-trino,1,2,0,0,0,3,11
9,presto-cassandra-server,1,2,0,0,0,3,11
13,trino-coral,0,2,1,1,0,4,9
23,trino-verifier-queries,0,1,0,2,0,3,7

In [11]:
repository_risk.describe()

normalized_severity,critical_count,high_count,low_count,medium_count,unknown_count,total_vulnerabilities,risk_score
count,27.000000,27.000000,27.000000,27.000000,27.0,27.000000,27.000000
mean,1.481481,10.666667,3.444444,12.000000,0.0,27.592593,66.851852
std,2.722702,27.185969,12.953566,26.834249,0.0,68.631827,158.519036
min,0.000000,0.000000,0.000000,0.000000,0.0,1.000000,2.000000
25%,0.000000,1.000000,0.000000,1.000000,0.0,3.000000,7.000000
50%,0.000000,2.000000,1.000000,3.000000,0.0,9.000000,21.000000
75%,2.000000,7.500000,1.000000,12.000000,0.0,22.000000,50.000000
max,12.000000,142.000000,68.000000,138.000000,0.0,360.000000,830.000000