In [ ]:
from scripts.metrics import MetricsBuilder
from scripts.load_data import DataLoader
import sys
from pathlib import Path

ANALYZER_DIR = Path.cwd().parent

# priorizar analyzer/ en imports
sys.path.insert(0, str(ANALYZER_DIR.resolve()))

# eliminar conflicto con namespace package "scripts"
for module in list(sys.modules):
    if module == "scripts" or module.startswith("scripts."):
        del sys.modules[module]


loader = DataLoader().load_all()

metrics = MetricsBuilder(loader)

In [2]:
repository_codeql_stats = (
    metrics.repository_codeql_stats()
)

repository_codeql_stats.head(20)

,repository_id,total_code_vulnerabilities,unique_rules,high_severity_findings,medium_severity_findings
0,539489521a87dff7364bcf49dcb350dcbdebac92,22,8,0,22
1,8d2730953f62a400e1feac6a6716a606d6bc2be8,1,1,0,1

In [3]:
top_cwes = (
    metrics.top_cwes()
)

top_cwes.head(20)

              cwe  frequency  repositories_affected  average_cvss  max_cvss
15         CWE-20         97                      6      4.257732       9.8
10       CWE-1333         61                      6      6.377049       8.7
76        CWE-770         59                     10      6.872881       8.9
45        CWE-400         58                     12      6.758621       7.5
54        CWE-444         43                      5      7.321622       7.5
9        CWE-1321         24                      5      6.637500       8.9
31        CWE-295         22                      3      7.672727      10.0
79         CWE-79         19                      4      6.278947       6.9
20         CWE-22         17                      4      5.811765       8.2
90         CWE-94         14                      5      8.285714       9.1
62         CWE-59         14                      6      6.614286       9.8
91  NVD-CWE-Other         14                      5      7.100000       9.8
56        CWE-502         13                      5      8.946154      10.0
4         CWE-125         10                      3      7.970000       8.8
68        CWE-674         10                      8      6.560000       7.5
17        CWE-201         10                      3      7.920000       8.2
85        CWE-863         10                      4      8.540000       8.8
78        CWE-787          9                      5      9.155556       9.8
48        CWE-409          9                      4      7.255556       8.9
44        CWE-378          9                      8      3.300000       3.3